import os
import sys
from google_auth_oauthlib.flow import InstalledAppFlow

# If modifying these scopes, delete the file secrets/google_calendar_token.json.
SCOPES = ['https://www.googleapis.com/auth/calendar']

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 finish_auth.py <code>")
        return
    
    code = sys.argv[1]
    token_path = 'secrets/google_calendar_token.json'
    creds_path = 'secrets/google_calendar_credentials.json'

    flow = InstalledAppFlow.from_client_secrets_file(
        creds_path, 
        SCOPES,
        redirect_uri='urn:ietf:wg:oauth:2.0:oob'
    )
    
    # We need the flow to have the same state/challenge if we were continuing,
    # but since we're starting a new flow, we might need Ronnie to use a NEW url
    # generated by THIS script to ensure the code matches.
    
    # Actually, if I run auth.py again with pty=true and wait, I can send the keys.
    
    auth_url, _ = flow.authorization_url(prompt='consent')
    print(auth_url)

if __name__ == '__main__':
    main()
